"""Model package.

Importing this module registers every table on ``Base.metadata``, which is what
Alembic autogenerate and the test-database bootstrap rely on.

:mod:`app.models.knowledge` is imported too. Its read-only knowledge-base
mappings join the same registry and metadata, which is what lets an application
table declare a real ``ForeignKey('sources.id')`` and lets an ORM relationship
name ``Source``. Alembic still never *emits* them: ``include_object`` in
``alembic/env.py`` returns False for any table outside the application
allow-list. They are deliberately absent from ``__all__`` so application code
cannot import a knowledge model by accident.
"""

from __future__ import annotations

from app.database.session import Base
from app.models.base import (
    SoftDeleteMixin,
    TimestampMixin,
    UUIDPrimaryKeyMixin,
    new_uuid,
    utcnow,
)
from app.models.diagnosis import (
    Diagnosis,
    DiagnosisAction,
    DiagnosisImage,
    DiagnosisResult,
    DiagnosisSymptom,
    VerifiedKnowledgeLink,
)
from app.models.enums import (
    BackupKind,
    BackupStatus,
    ClientPlatform,
    DiagnosisStatus,
    EvidenceSource,
    FileKind,
    HealthGrade,
    OtpPurpose,
    RecordStatus,
    ResultKind,
    SessionRevokeReason,
    SettingValueType,
    UserStatus,
    VerificationChannel,
)
from app.models.experts import (
    Doctor,
    DoctorCredential,
    DoctorSpecialization,
    DoctorSpecializationLink,
    Expert,
)
from app.models.files import StoredFile
from app.models.governance import (
    AdminAction,
    AuditLog,
    DataImportBatch,
    DataVerification,
    DatabaseBackup,
    Notification,
    SourceReference,
    SystemSetting,
)
from app.models.identity import (
    Permission,
    Role,
    RolePermission,
    User,
    UserProfile,
    UserRole,
)
from app.models.otp import OtpAttempt, OtpRequest
from app.models.session import LoginAttempt, RefreshToken, StateVersion, UserSession
from app.models.user_content import PlantHealthHistory, SavedPlant, UserPlantNote

# Registers the read-only knowledge-base mappings on the shared registry.
import app.models.knowledge as _knowledge  # noqa: E402,F401

#: The only tables Alembic is allowed to create, alter or drop.
#:
#: This is the single source of truth. ``alembic/env.py`` imports it for
#: ``include_object``, so autogenerate can never propose touching a
#: knowledge-base table, and a new application table fails loudly here until it
#: is explicitly listed.
APPLICATION_TABLES = frozenset(
    {
        "users",
        "user_profiles",
        "roles",
        "permissions",
        "user_roles",
        "role_permissions",
        "user_sessions",
        "refresh_tokens",
        "user_state_versions",
        "login_attempts",
        "otp_requests",
        "otp_attempts",
        "stored_files",
        "doctors",
        "doctor_specializations",
        "doctor_specialization_links",
        "doctor_credentials",
        "experts",
        "diagnoses",
        "diagnosis_images",
        "diagnosis_results",
        "diagnosis_symptoms",
        "diagnosis_actions",
        "verified_knowledge_links",
        "saved_plants",
        "user_plant_notes",
        "plant_health_history",
        "data_verification",
        "source_references",
        "notifications",
        "audit_logs",
        "admin_actions",
        "system_settings",
        "database_backups",
        "data_import_batches",
    }
)

#: Never autogenerated even if listed above.
RESERVED_TABLES = frozenset({"alembic_version", "schema_migrations"})

__all__ = [
    "APPLICATION_TABLES",
    "AdminAction",
    "AuditLog",
    "BackupKind",
    "BackupStatus",
    "Base",
    "ClientPlatform",
    "DataImportBatch",
    "DataVerification",
    "DatabaseBackup",
    "Diagnosis",
    "DiagnosisAction",
    "DiagnosisImage",
    "DiagnosisResult",
    "DiagnosisStatus",
    "DiagnosisSymptom",
    "Doctor",
    "DoctorCredential",
    "DoctorSpecialization",
    "DoctorSpecializationLink",
    "EvidenceSource",
    "Expert",
    "FileKind",
    "HealthGrade",
    "LoginAttempt",
    "Notification",
    "OtpAttempt",
    "OtpPurpose",
    "OtpRequest",
    "Permission",
    "PlantHealthHistory",
    "RecordStatus",
    "RefreshToken",
    "ResultKind",
    "Role",
    "RolePermission",
    "SavedPlant",
    "SessionRevokeReason",
    "SettingValueType",
    "SourceReference",
    "StateVersion",
    "StoredFile",
    "SystemSetting",
    "SoftDeleteMixin",
    "TimestampMixin",
    "UUIDPrimaryKeyMixin",
    "User",
    "UserPlantNote",
    "UserProfile",
    "UserRole",
    "UserSession",
    "UserStatus",
    "VerificationChannel",
    "VerifiedKnowledgeLink",
    "new_uuid",
    "utcnow",
]
