"""Initial application schema: identity, sessions, OTP, files, experts,
diagnosis, user content and governance.

Creates 35 tables for the application domain. It touches **no**
knowledge-base table: those are owned by ``backend/migrations/*.sql`` and
must be applied first (``python scripts/migrate.py up``).

References from application tables into the knowledge base (``plants``,
``diseases``, ``symptoms``, ``pests``, ``treatments``,
``treatment_products``, ``sources``) are declared as real foreign keys, so
a knowledge row cannot be deleted while an application row still points at
it.

Downgrade drops only application tables, in reverse dependency order.

Revision ID: 7fbfc616480e
Revises: 
Create Date: 2026-09-27 15:18:13.566417
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '0001_initial'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_specializations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('plant_disciplines', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_doctor_specialization_code')
    )
    op.create_index(op.f('ix_doctor_specializations_code'), 'doctor_specializations', ['code'], unique=True)
    op.create_index(op.f('ix_doctor_specializations_created_at'), 'doctor_specializations', ['created_at'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('resource', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_dangerous', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource', 'action', name='uq_permissions_resource_action')
    )
    op.create_index(op.f('ix_permissions_action'), 'permissions', ['action'], unique=False)
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_index(op.f('ix_permissions_created_at'), 'permissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_permissions_resource'), 'permissions', ['resource'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('priority', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_created_at'), 'roles', ['created_at'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('email_normalised', sa.String(length=320), nullable=True),
    sa.Column('phone_e164', sa.String(length=20), nullable=True),
    sa.Column('phone_display', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phone_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_staff', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_export_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_staff'), 'users', ['is_staff'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index('ix_users_status_email', 'users', ['status', 'email_normalised'], unique=False)
    op.create_index('uq_users_email_normalised_active', 'users', ['email_normalised'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND email_normalised IS NOT NULL'))
    op.create_index('uq_users_phone_e164_active', 'users', ['phone_e164'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND phone_e164 IS NOT NULL'))
    op.create_table('admin_actions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('admin_user_id', sa.UUID(), nullable=True),
    sa.Column('admin_email', sa.String(length=320), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=60), nullable=False),
    sa.Column('target_id', sa.String(length=80), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('affected_user_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['affected_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_actions_action'), 'admin_actions', ['action'], unique=False)
    op.create_index('ix_admin_actions_admin_time', 'admin_actions', ['admin_user_id', 'performed_at'], unique=False)
    op.create_index(op.f('ix_admin_actions_admin_user_id'), 'admin_actions', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_admin_actions_performed_at'), 'admin_actions', ['performed_at'], unique=False)
    op.create_index(op.f('ix_admin_actions_target_type'), 'admin_actions', ['target_type'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_email', sa.String(length=320), nullable=True),
    sa.Column('actor_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=60), nullable=False),
    sa.Column('resource_id', sa.String(length=80), nullable=True),
    sa.Column('http_method', sa.String(length=10), nullable=True),
    sa.Column('route', sa.String(length=200), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('is_dangerous', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_actor_time', 'audit_logs', ['actor_user_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_is_dangerous'), 'audit_logs', ['is_dangerous'], unique=False)
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index('ix_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_table('data_import_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('source_file', sa.String(length=400), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('knowledge_batch_id', sa.Integer(), nullable=True),
    sa.Column('records_seen', sa.Integer(), nullable=False),
    sa.Column('records_inserted', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_rejected', sa.Integer(), nullable=False),
    sa.Column('was_dry_run', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_import_batches_created_at'), 'data_import_batches', ['created_at'], unique=False)
    op.create_index(op.f('ix_data_import_batches_entity_type'), 'data_import_batches', ['entity_type'], unique=False)
    op.create_index(op.f('ix_data_import_batches_source_sha256'), 'data_import_batches', ['source_sha256'], unique=False)
    op.create_table('data_verification',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_uuid', sa.Uuid(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('entity_label', sa.String(length=240), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('field_name', sa.String(length=80), nullable=True),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_citation', sa.Text(), nullable=True),
    sa.Column('evidence_excerpt', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verification_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_verification_created_at'), 'data_verification', ['created_at'], unique=False)
    op.create_index(op.f('ix_data_verification_entity_id'), 'data_verification', ['entity_id'], unique=False)
    op.create_index(op.f('ix_data_verification_entity_type'), 'data_verification', ['entity_type'], unique=False)
    op.create_index(op.f('ix_data_verification_entity_uuid'), 'data_verification', ['entity_uuid'], unique=False)
    op.create_index('ix_data_verification_queue', 'data_verification', ['entity_type', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_data_verification_source_id'), 'data_verification', ['source_id'], unique=False)
    op.create_index(op.f('ix_data_verification_status'), 'data_verification', ['status'], unique=False)
    op.create_index(op.f('ix_data_verification_verification_date'), 'data_verification', ['verification_date'], unique=False)
    op.create_index('uq_data_verification_live', 'data_verification', ['entity_type', 'entity_id', 'field_name'], unique=True, postgresql_where=sa.text('entity_id IS NOT NULL'))
    op.create_table('database_backups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('relative_path', sa.String(length=400), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('compression', sa.String(length=16), nullable=True),
    sa.Column('schema_revision', sa.String(length=64), nullable=True),
    sa.Column('knowledge_migrations', sa.Integer(), nullable=True),
    sa.Column('table_row_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_database_backups_created_at'), 'database_backups', ['created_at'], unique=False)
    op.create_index(op.f('ix_database_backups_filename'), 'database_backups', ['filename'], unique=True)
    op.create_index(op.f('ix_database_backups_sha256'), 'database_backups', ['sha256'], unique=False)
    op.create_index(op.f('ix_database_backups_status'), 'database_backups', ['status'], unique=False)
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('email_normalised', sa.String(length=320), nullable=True),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=64), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_attempted_at'), 'login_attempts', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_email_normalised'), 'login_attempts', ['email_normalised'], unique=False)
    op.create_index('ix_login_attempts_lookup', 'login_attempts', ['email_normalised', 'attempted_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_succeeded'), 'login_attempts', ['succeeded'], unique=False)
    op.create_index(op.f('ix_login_attempts_user_id'), 'login_attempts', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_read_at'), 'notifications', ['read_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'read_at', 'created_at'], unique=False)
    op.create_table('otp_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=8), nullable=False),
    sa.Column('target', sa.String(length=320), nullable=False),
    sa.Column('target_hash', sa.String(length=64), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('attempts_used', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('resend_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_resends', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidated_reason', sa.String(length=64), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('delivery_reference', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_requests_channel'), 'otp_requests', ['channel'], unique=False)
    op.create_index(op.f('ix_otp_requests_consumed_at'), 'otp_requests', ['consumed_at'], unique=False)
    op.create_index(op.f('ix_otp_requests_created_at'), 'otp_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_otp_requests_expires_at'), 'otp_requests', ['expires_at'], unique=False)
    op.create_index('ix_otp_requests_lookup', 'otp_requests', ['target_hash', 'purpose', 'expires_at'], unique=False)
    op.create_index('ix_otp_requests_pending', 'otp_requests', ['target_hash', 'purpose'], unique=False, postgresql_where=sa.text('consumed_at IS NULL AND invalidated_at IS NULL'))
    op.create_index(op.f('ix_otp_requests_purpose'), 'otp_requests', ['purpose'], unique=False)
    op.create_index(op.f('ix_otp_requests_target_hash'), 'otp_requests', ['target_hash'], unique=False)
    op.create_index(op.f('ix_otp_requests_user_id'), 'otp_requests', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('source_references',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('citation', sa.Text(), nullable=True),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.Column('published_on', sa.Date(), nullable=True),
    sa.Column('accessed_on', sa.Date(), nullable=True),
    sa.Column('page_reference', sa.String(length=120), nullable=True),
    sa.Column('license_name', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_references_created_at'), 'source_references', ['created_at'], unique=False)
    op.create_index(op.f('ix_source_references_source_id'), 'source_references', ['source_id'], unique=False)
    op.create_table('stored_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('storage_backend', sa.String(length=32), server_default=sa.text("'filesystem'"), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('safe_filename', sa.String(length=160), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('content_type_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_processed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_stored_files_created_at'), 'stored_files', ['created_at'], unique=False)
    op.create_index(op.f('ix_stored_files_deleted_at'), 'stored_files', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_stored_files_kind'), 'stored_files', ['kind'], unique=False)
    op.create_index('ix_stored_files_live', 'stored_files', ['kind'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_stored_files_mime_type'), 'stored_files', ['mime_type'], unique=False)
    op.create_index('ix_stored_files_owner_kind', 'stored_files', ['owner_user_id', 'kind'], unique=False)
    op.create_index(op.f('ix_stored_files_owner_user_id'), 'stored_files', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_stored_files_sha256'), 'stored_files', ['sha256'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('value_type', sa.String(length=16), nullable=False),
    sa.Column('is_secret', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('restart_required', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_created_at'), 'system_settings', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.create_table('user_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    op.create_index(op.f('ix_user_roles_created_at'), 'user_roles', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_token_hash', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=True),
    sa.Column('device_name', sa.String(length=120), nullable=True),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('app_version', sa.String(length=32), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=24), nullable=True),
    sa.Column('refresh_rotations', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_created_at'), 'user_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_device_id'), 'user_sessions', ['device_id'], unique=False)
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_last_seen_at'), 'user_sessions', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_platform'), 'user_sessions', ['platform'], unique=False)
    op.create_index(op.f('ix_user_sessions_revoked_at'), 'user_sessions', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_session_token_hash'), 'user_sessions', ['session_token_hash'], unique=False)
    op.create_index('ix_user_sessions_user_active', 'user_sessions', ['user_id', 'revoked_at', 'expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('user_state_versions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('doctors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('qualifications', sa.String(length=300), nullable=True),
    sa.Column('designation', sa.String(length=120), nullable=True),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('organization_type', sa.String(length=60), nullable=True),
    sa.Column('expertise_summary', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('service_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('languages_spoken', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('public_email', sa.String(length=320), nullable=True),
    sa.Column('public_phone_e164', sa.String(length=20), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('profile_image_file_id', sa.UUID(), nullable=True),
    sa.Column('consultation_available', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('consultation_mode', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('consultation_notes', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=16), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_citation', sa.Text(), nullable=True),
    sa.Column('license_jurisdiction', sa.String(length=120), nullable=True),
    sa.Column('license_status', sa.String(length=60), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_image_file_id'], ['stored_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctors_country_code'), 'doctors', ['country_code'], unique=False)
    op.create_index(op.f('ix_doctors_created_at'), 'doctors', ['created_at'], unique=False)
    op.create_index(op.f('ix_doctors_deleted_at'), 'doctors', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_doctors_full_name'), 'doctors', ['full_name'], unique=False)
    op.create_index('ix_doctors_location', 'doctors', ['country_code', 'region'], unique=False)
    op.create_index(op.f('ix_doctors_organization'), 'doctors', ['organization'], unique=False)
    op.create_index('ix_doctors_public', 'doctors', ['verification_status', 'full_name'], unique=False, postgresql_where=sa.text("deleted_at IS NULL AND verification_status = 'VERIFIED'"))
    op.create_index(op.f('ix_doctors_source_id'), 'doctors', ['source_id'], unique=False)
    op.create_index(op.f('ix_doctors_verification_status'), 'doctors', ['verification_status'], unique=False)
    op.create_table('otp_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('otp_request_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=64), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['otp_request_id'], ['otp_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_attempts_created_at'), 'otp_attempts', ['created_at'], unique=False)
    op.create_index(op.f('ix_otp_attempts_otp_request_id'), 'otp_attempts', ['otp_request_id'], unique=False)
    op.create_index('ix_otp_attempts_request', 'otp_attempts', ['otp_request_id', 'attempt_number'], unique=True)
    op.create_index(op.f('ix_otp_attempts_succeeded'), 'otp_attempts', ['succeeded'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=24), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('replaced_by_id', sa.UUID(), nullable=True),
    sa.Column('is_rotated', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['refresh_tokens.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['refresh_tokens.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_index(op.f('ix_refresh_tokens_created_at'), 'refresh_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_is_rotated'), 'refresh_tokens', ['is_rotated'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_revoked_at'), 'refresh_tokens', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_session_id'), 'refresh_tokens', ['session_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index('ix_refresh_tokens_user_active', 'refresh_tokens', ['user_id', 'revoked_at', 'expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('saved_plants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('nickname', sa.String(length=80), nullable=False),
    sa.Column('plant_id', sa.BigInteger(), nullable=True),
    sa.Column('common_name', sa.String(length=160), nullable=True),
    sa.Column('scientific_name_claimed', sa.String(length=200), nullable=True),
    sa.Column('variety', sa.String(length=120), nullable=True),
    sa.Column('identity_notes', sa.String(length=300), nullable=True),
    sa.Column('image_file_id', sa.UUID(), nullable=True),
    sa.Column('location_note', sa.String(length=200), nullable=True),
    sa.Column('is_potted', sa.Boolean(), nullable=True),
    sa.Column('is_outdoor', sa.Boolean(), nullable=True),
    sa.Column('planted_on', sa.Date(), nullable=True),
    sa.Column('acquired_on', sa.Date(), nullable=True),
    sa.Column('expected_harvest_on', sa.Date(), nullable=True),
    sa.Column('health_status', sa.String(length=24), nullable=True),
    sa.Column('latest_health_index', sa.Integer(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('care_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['image_file_id'], ['stored_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_plants_created_at'), 'saved_plants', ['created_at'], unique=False)
    op.create_index(op.f('ix_saved_plants_deleted_at'), 'saved_plants', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_saved_plants_plant_id'), 'saved_plants', ['plant_id'], unique=False)
    op.create_index('ix_saved_plants_user_active', 'saved_plants', ['user_id', 'created_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_saved_plants_user_id'), 'saved_plants', ['user_id'], unique=False)
    op.create_index('uq_saved_plants_user_nickname', 'saved_plants', ['user_id', 'nickname'], unique=True)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('avatar_file_id', sa.UUID(), nullable=True),
    sa.Column('locale', sa.String(length=12), server_default=sa.text("'en-IN'"), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default=sa.text("'Asia/Kolkata'"), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('experience_level', sa.String(length=40), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('notification_preferences', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['avatar_file_id'], ['stored_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_created_at'), 'user_profiles', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('diagnoses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('status_detail', sa.String(length=200), nullable=True),
    sa.Column('model_name', sa.String(length=80), nullable=True),
    sa.Column('model_version', sa.String(length=40), nullable=True),
    sa.Column('analysis_location', sa.String(length=16), server_default=sa.text("'client'"), nullable=False),
    sa.Column('analysis_duration_ms', sa.Integer(), nullable=True),
    sa.Column('client_app_version', sa.String(length=32), nullable=True),
    sa.Column('device_id', sa.String(length=128), nullable=True),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('user_reported_symptoms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('region_hint', sa.String(length=120), nullable=True),
    sa.Column('health_index', sa.Integer(), nullable=True),
    sa.Column('health_grade', sa.String(length=24), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=200), nullable=True),
    sa.Column('saved_plant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['saved_plant_id'], ['saved_plants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_diagnoses_active', 'diagnoses', ['user_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_diagnoses_created_at'), 'diagnoses', ['created_at'], unique=False)
    op.create_index(op.f('ix_diagnoses_deleted_at'), 'diagnoses', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_diagnoses_saved_plant_id'), 'diagnoses', ['saved_plant_id'], unique=False)
    op.create_index(op.f('ix_diagnoses_status'), 'diagnoses', ['status'], unique=False)
    op.create_index('ix_diagnoses_user_created', 'diagnoses', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_diagnoses_user_id'), 'diagnoses', ['user_id'], unique=False)
    op.create_table('doctor_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('credential_type', sa.String(length=60), nullable=False),
    sa.Column('credential_name', sa.String(length=200), nullable=False),
    sa.Column('issuing_body', sa.String(length=200), nullable=True),
    sa.Column('license_number', sa.String(length=120), nullable=True),
    sa.Column('jurisdiction', sa.String(length=120), nullable=True),
    sa.Column('issued_on', sa.Date(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('verification_status', sa.String(length=16), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('document_reference', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_credentials_created_at'), 'doctor_credentials', ['created_at'], unique=False)
    op.create_index(op.f('ix_doctor_credentials_credential_type'), 'doctor_credentials', ['credential_type'], unique=False)
    op.create_index(op.f('ix_doctor_credentials_doctor_id'), 'doctor_credentials', ['doctor_id'], unique=False)
    op.create_table('doctor_specialization_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('specialization_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('years_in_field', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialization_id'], ['doctor_specializations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'specialization_id', name='uq_doctor_specialization')
    )
    op.create_index(op.f('ix_doctor_specialization_links_doctor_id'), 'doctor_specialization_links', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_specialization_links_specialization_id'), 'doctor_specialization_links', ['specialization_id'], unique=False)
    op.create_table('experts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('expertise_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('can_review_knowledge', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('can_review_diagnoses', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('hourly_rate_note', sa.String(length=200), nullable=True),
    sa.Column('is_accepting_cases', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_experts_active', 'experts', ['is_accepting_cases'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_experts_created_at'), 'experts', ['created_at'], unique=False)
    op.create_index(op.f('ix_experts_deleted_at'), 'experts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_experts_doctor_id'), 'experts', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_experts_user_id'), 'experts', ['user_id'], unique=True)
    op.create_table('user_plant_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_plant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('observed_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_file_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['image_file_id'], ['stored_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_plant_id'], ['saved_plants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_plant_notes_created_at'), 'user_plant_notes', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_plant_notes_deleted_at'), 'user_plant_notes', ['deleted_at'], unique=False)
    op.create_index('ix_user_plant_notes_plant', 'user_plant_notes', ['user_plant_id', 'observed_on'], unique=False)
    op.create_index(op.f('ix_user_plant_notes_user_id'), 'user_plant_notes', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_plant_notes_user_plant_id'), 'user_plant_notes', ['user_plant_id'], unique=False)
    op.create_table('diagnosis_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=48), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('urgency', sa.String(length=16), server_default=sa.text("'routine'"), nullable=False),
    sa.Column('is_medical_advice', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('source_reference_id', sa.UUID(), nullable=True),
    sa.Column('source_name', sa.String(length=200), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_reference_id'], ['source_references.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_actions_action_type'), 'diagnosis_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_diagnosis_actions_diagnosis_id'), 'diagnosis_actions', ['diagnosis_id'], unique=False)
    op.create_index('ix_diagnosis_actions_order', 'diagnosis_actions', ['diagnosis_id', 'sort_order'], unique=False)
    op.create_table('diagnosis_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=False),
    sa.Column('stored_file_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=24), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_quality', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('client_measurements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stored_file_id'], ['stored_files.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_images_created_at'), 'diagnosis_images', ['created_at'], unique=False)
    op.create_index(op.f('ix_diagnosis_images_diagnosis_id'), 'diagnosis_images', ['diagnosis_id'], unique=False)
    op.create_index(op.f('ix_diagnosis_images_stored_file_id'), 'diagnosis_images', ['stored_file_id'], unique=False)
    op.create_index('uq_diagnosis_image_position', 'diagnosis_images', ['diagnosis_id', 'position'], unique=True)
    op.create_table('diagnosis_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('is_prediction', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('evidence_source', sa.String(length=24), nullable=False),
    sa.Column('model_name', sa.String(length=80), nullable=True),
    sa.Column('model_version', sa.String(length=40), nullable=True),
    sa.Column('raw_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('candidate_disease_id', sa.BigInteger(), nullable=True),
    sa.Column('candidate_plant_id', sa.BigInteger(), nullable=True),
    sa.Column('candidate_pest_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_disease_id'], ['diseases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['candidate_pest_id'], ['pests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['candidate_plant_id'], ['plants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_results_candidate_disease_id'), 'diagnosis_results', ['candidate_disease_id'], unique=False)
    op.create_index(op.f('ix_diagnosis_results_candidate_pest_id'), 'diagnosis_results', ['candidate_pest_id'], unique=False)
    op.create_index(op.f('ix_diagnosis_results_candidate_plant_id'), 'diagnosis_results', ['candidate_plant_id'], unique=False)
    op.create_index(op.f('ix_diagnosis_results_created_at'), 'diagnosis_results', ['created_at'], unique=False)
    op.create_index('ix_diagnosis_results_diag_kind_rank', 'diagnosis_results', ['diagnosis_id', 'kind', 'rank'], unique=False)
    op.create_index(op.f('ix_diagnosis_results_diagnosis_id'), 'diagnosis_results', ['diagnosis_id'], unique=False)
    op.create_index(op.f('ix_diagnosis_results_kind'), 'diagnosis_results', ['kind'], unique=False)
    op.create_table('plant_health_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_plant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=True),
    sa.Column('health_index', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=24), nullable=True),
    sa.Column('source', sa.String(length=32), server_default=sa.text("'client_engine'"), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_plant_id'], ['saved_plants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_health_history_plant', 'plant_health_history', ['user_plant_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_plant_health_history_diagnosis_id'), 'plant_health_history', ['diagnosis_id'], unique=False)
    op.create_index(op.f('ix_plant_health_history_user_id'), 'plant_health_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_plant_health_history_user_plant_id'), 'plant_health_history', ['user_plant_id'], unique=False)
    op.create_table('verified_knowledge_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=24), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('entity_label', sa.String(length=200), nullable=False),
    sa.Column('entity_verification_status', sa.String(length=16), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('source_name', sa.String(length=200), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verified_knowledge_links_diagnosis_id'), 'verified_knowledge_links', ['diagnosis_id'], unique=False)
    op.create_index(op.f('ix_verified_knowledge_links_entity_type'), 'verified_knowledge_links', ['entity_type'], unique=False)
    op.create_index('uq_verified_link', 'verified_knowledge_links', ['diagnosis_id', 'entity_type', 'entity_id'], unique=True)
    op.create_table('diagnosis_symptoms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('result_id', sa.UUID(), nullable=False),
    sa.Column('symptom_id', sa.BigInteger(), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('part', sa.String(length=24), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('evidence_source', sa.String(length=24), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['diagnosis_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_symptoms_result_id'), 'diagnosis_symptoms', ['result_id'], unique=False)
    op.create_index(op.f('ix_diagnosis_symptoms_symptom_id'), 'diagnosis_symptoms', ['symptom_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diagnosis_symptoms_symptom_id'), table_name='diagnosis_symptoms')
    op.drop_index(op.f('ix_diagnosis_symptoms_result_id'), table_name='diagnosis_symptoms')
    op.drop_table('diagnosis_symptoms')
    op.drop_index('uq_verified_link', table_name='verified_knowledge_links')
    op.drop_index(op.f('ix_verified_knowledge_links_entity_type'), table_name='verified_knowledge_links')
    op.drop_index(op.f('ix_verified_knowledge_links_diagnosis_id'), table_name='verified_knowledge_links')
    op.drop_table('verified_knowledge_links')
    op.drop_index(op.f('ix_plant_health_history_user_plant_id'), table_name='plant_health_history')
    op.drop_index(op.f('ix_plant_health_history_user_id'), table_name='plant_health_history')
    op.drop_index(op.f('ix_plant_health_history_diagnosis_id'), table_name='plant_health_history')
    op.drop_index('ix_health_history_plant', table_name='plant_health_history')
    op.drop_table('plant_health_history')
    op.drop_index(op.f('ix_diagnosis_results_kind'), table_name='diagnosis_results')
    op.drop_index(op.f('ix_diagnosis_results_diagnosis_id'), table_name='diagnosis_results')
    op.drop_index('ix_diagnosis_results_diag_kind_rank', table_name='diagnosis_results')
    op.drop_index(op.f('ix_diagnosis_results_created_at'), table_name='diagnosis_results')
    op.drop_index(op.f('ix_diagnosis_results_candidate_plant_id'), table_name='diagnosis_results')
    op.drop_index(op.f('ix_diagnosis_results_candidate_pest_id'), table_name='diagnosis_results')
    op.drop_index(op.f('ix_diagnosis_results_candidate_disease_id'), table_name='diagnosis_results')
    op.drop_table('diagnosis_results')
    op.drop_index('uq_diagnosis_image_position', table_name='diagnosis_images')
    op.drop_index(op.f('ix_diagnosis_images_stored_file_id'), table_name='diagnosis_images')
    op.drop_index(op.f('ix_diagnosis_images_diagnosis_id'), table_name='diagnosis_images')
    op.drop_index(op.f('ix_diagnosis_images_created_at'), table_name='diagnosis_images')
    op.drop_table('diagnosis_images')
    op.drop_index('ix_diagnosis_actions_order', table_name='diagnosis_actions')
    op.drop_index(op.f('ix_diagnosis_actions_diagnosis_id'), table_name='diagnosis_actions')
    op.drop_index(op.f('ix_diagnosis_actions_action_type'), table_name='diagnosis_actions')
    op.drop_table('diagnosis_actions')
    op.drop_index(op.f('ix_user_plant_notes_user_plant_id'), table_name='user_plant_notes')
    op.drop_index(op.f('ix_user_plant_notes_user_id'), table_name='user_plant_notes')
    op.drop_index('ix_user_plant_notes_plant', table_name='user_plant_notes')
    op.drop_index(op.f('ix_user_plant_notes_deleted_at'), table_name='user_plant_notes')
    op.drop_index(op.f('ix_user_plant_notes_created_at'), table_name='user_plant_notes')
    op.drop_table('user_plant_notes')
    op.drop_index(op.f('ix_experts_user_id'), table_name='experts')
    op.drop_index(op.f('ix_experts_doctor_id'), table_name='experts')
    op.drop_index(op.f('ix_experts_deleted_at'), table_name='experts')
    op.drop_index(op.f('ix_experts_created_at'), table_name='experts')
    op.drop_index('ix_experts_active', table_name='experts', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('experts')
    op.drop_index(op.f('ix_doctor_specialization_links_specialization_id'), table_name='doctor_specialization_links')
    op.drop_index(op.f('ix_doctor_specialization_links_doctor_id'), table_name='doctor_specialization_links')
    op.drop_table('doctor_specialization_links')
    op.drop_index(op.f('ix_doctor_credentials_doctor_id'), table_name='doctor_credentials')
    op.drop_index(op.f('ix_doctor_credentials_credential_type'), table_name='doctor_credentials')
    op.drop_index(op.f('ix_doctor_credentials_created_at'), table_name='doctor_credentials')
    op.drop_table('doctor_credentials')
    op.drop_index(op.f('ix_diagnoses_user_id'), table_name='diagnoses')
    op.drop_index('ix_diagnoses_user_created', table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_status'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_saved_plant_id'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_deleted_at'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_created_at'), table_name='diagnoses')
    op.drop_index('ix_diagnoses_active', table_name='diagnoses', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('diagnoses')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_created_at'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index('uq_saved_plants_user_nickname', table_name='saved_plants')
    op.drop_index(op.f('ix_saved_plants_user_id'), table_name='saved_plants')
    op.drop_index('ix_saved_plants_user_active', table_name='saved_plants', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_saved_plants_plant_id'), table_name='saved_plants')
    op.drop_index(op.f('ix_saved_plants_deleted_at'), table_name='saved_plants')
    op.drop_index(op.f('ix_saved_plants_created_at'), table_name='saved_plants')
    op.drop_table('saved_plants')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_user_active', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_session_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_revoked_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_is_rotated'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_created_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_otp_attempts_succeeded'), table_name='otp_attempts')
    op.drop_index('ix_otp_attempts_request', table_name='otp_attempts')
    op.drop_index(op.f('ix_otp_attempts_otp_request_id'), table_name='otp_attempts')
    op.drop_index(op.f('ix_otp_attempts_created_at'), table_name='otp_attempts')
    op.drop_table('otp_attempts')
    op.drop_index(op.f('ix_doctors_verification_status'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_source_id'), table_name='doctors')
    op.drop_index('ix_doctors_public', table_name='doctors', postgresql_where=sa.text("deleted_at IS NULL AND verification_status = 'VERIFIED'"))
    op.drop_index(op.f('ix_doctors_organization'), table_name='doctors')
    op.drop_index('ix_doctors_location', table_name='doctors')
    op.drop_index(op.f('ix_doctors_full_name'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_deleted_at'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_created_at'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_country_code'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_table('user_state_versions')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index('ix_user_sessions_user_active', table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_session_token_hash'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_revoked_at'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_platform'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_last_seen_at'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_device_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_created_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_created_at'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_created_at'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_stored_files_sha256'), table_name='stored_files')
    op.drop_index(op.f('ix_stored_files_owner_user_id'), table_name='stored_files')
    op.drop_index('ix_stored_files_owner_kind', table_name='stored_files')
    op.drop_index(op.f('ix_stored_files_mime_type'), table_name='stored_files')
    op.drop_index('ix_stored_files_live', table_name='stored_files', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_stored_files_kind'), table_name='stored_files')
    op.drop_index(op.f('ix_stored_files_deleted_at'), table_name='stored_files')
    op.drop_index(op.f('ix_stored_files_created_at'), table_name='stored_files')
    op.drop_table('stored_files')
    op.drop_index(op.f('ix_source_references_source_id'), table_name='source_references')
    op.drop_index(op.f('ix_source_references_created_at'), table_name='source_references')
    op.drop_table('source_references')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_otp_requests_user_id'), table_name='otp_requests')
    op.drop_index(op.f('ix_otp_requests_target_hash'), table_name='otp_requests')
    op.drop_index(op.f('ix_otp_requests_purpose'), table_name='otp_requests')
    op.drop_index('ix_otp_requests_pending', table_name='otp_requests', postgresql_where=sa.text('consumed_at IS NULL AND invalidated_at IS NULL'))
    op.drop_index('ix_otp_requests_lookup', table_name='otp_requests')
    op.drop_index(op.f('ix_otp_requests_expires_at'), table_name='otp_requests')
    op.drop_index(op.f('ix_otp_requests_created_at'), table_name='otp_requests')
    op.drop_index(op.f('ix_otp_requests_consumed_at'), table_name='otp_requests')
    op.drop_index(op.f('ix_otp_requests_channel'), table_name='otp_requests')
    op.drop_table('otp_requests')
    op.drop_index('ix_notifications_user_unread', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_read_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_login_attempts_user_id'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_succeeded'), table_name='login_attempts')
    op.drop_index('ix_login_attempts_lookup', table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_email_normalised'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_attempted_at'), table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index(op.f('ix_database_backups_status'), table_name='database_backups')
    op.drop_index(op.f('ix_database_backups_sha256'), table_name='database_backups')
    op.drop_index(op.f('ix_database_backups_filename'), table_name='database_backups')
    op.drop_index(op.f('ix_database_backups_created_at'), table_name='database_backups')
    op.drop_table('database_backups')
    op.drop_index('uq_data_verification_live', table_name='data_verification', postgresql_where=sa.text('entity_id IS NOT NULL'))
    op.drop_index(op.f('ix_data_verification_verification_date'), table_name='data_verification')
    op.drop_index(op.f('ix_data_verification_status'), table_name='data_verification')
    op.drop_index(op.f('ix_data_verification_source_id'), table_name='data_verification')
    op.drop_index('ix_data_verification_queue', table_name='data_verification')
    op.drop_index(op.f('ix_data_verification_entity_uuid'), table_name='data_verification')
    op.drop_index(op.f('ix_data_verification_entity_type'), table_name='data_verification')
    op.drop_index(op.f('ix_data_verification_entity_id'), table_name='data_verification')
    op.drop_index(op.f('ix_data_verification_created_at'), table_name='data_verification')
    op.drop_table('data_verification')
    op.drop_index(op.f('ix_data_import_batches_source_sha256'), table_name='data_import_batches')
    op.drop_index(op.f('ix_data_import_batches_entity_type'), table_name='data_import_batches')
    op.drop_index(op.f('ix_data_import_batches_created_at'), table_name='data_import_batches')
    op.drop_table('data_import_batches')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_is_dangerous'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_time', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_admin_actions_target_type'), table_name='admin_actions')
    op.drop_index(op.f('ix_admin_actions_performed_at'), table_name='admin_actions')
    op.drop_index(op.f('ix_admin_actions_admin_user_id'), table_name='admin_actions')
    op.drop_index('ix_admin_actions_admin_time', table_name='admin_actions')
    op.drop_index(op.f('ix_admin_actions_action'), table_name='admin_actions')
    op.drop_table('admin_actions')
    op.drop_index('uq_users_phone_e164_active', table_name='users', postgresql_where=sa.text('deleted_at IS NULL AND phone_e164 IS NOT NULL'))
    op.drop_index('uq_users_email_normalised_active', table_name='users', postgresql_where=sa.text('deleted_at IS NULL AND email_normalised IS NOT NULL'))
    op.drop_index('ix_users_status_email', table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_is_staff'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_created_at'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_resource'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_created_at'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_action'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_doctor_specializations_created_at'), table_name='doctor_specializations')
    op.drop_index(op.f('ix_doctor_specializations_code'), table_name='doctor_specializations')
    op.drop_table('doctor_specializations')
    # ### end Alembic commands ###
