"""Make ``experts.user_id`` uniqueness actually enforce.

The column was ``UNIQUE`` and nullable. In SQL ``NULL <> NULL``, so a plain
UNIQUE index over a nullable column permits any number of NULL rows and
enforces nothing - the constraint looked active in every schema dump while
letting duplicate expert profiles through.

Replaced with a PARTIAL unique index over ``WHERE user_id IS NOT NULL``,
which states the real rule: an account may back at most one expert profile,
and any number of unlinked profiles may exist.

Revision ID: 069e68f84bbc
Revises: 0002_refresh_family
Create Date: 2026-09-27 15:29:12.001515
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0003_expert_user_unique'
down_revision: str | None = '0002_refresh_family'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_database_backups_status_started', 'database_backups', ['status', 'started_at'], unique=False)
    op.drop_index(op.f('ix_experts_user_id'), table_name='experts')
    op.create_index('uq_experts_user_id', 'experts', ['user_id'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_experts_user_id', table_name='experts', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.create_index(op.f('ix_experts_user_id'), 'experts', ['user_id'], unique=True)
    op.drop_index('ix_database_backups_status_started', table_name='database_backups')
    # ### end Alembic commands ###
