"""Add ``login_attempts.identifier_used`` and an IP/time index.

``UserService`` writes ``identifier_used=`` and ``was_successful=`` when it
logs a login outcome. Neither matched the model, which exposed
``email_normalised`` and ``succeeded``, so every real login raised TypeError
inside the authentication path. The mismatch was invisible in Phase 2
because nothing logged in.

``identifier_used`` holds the *masked* form, which is what may be shown in an
audit view or quoted to a user. The plaintext normalised address stays in
``email_normalised`` only because brute-force detection has to group attempts
by target address.

The second index covers the other half of that question: which addresses were
tried from one IP. The table is append-only and grows without bound, so the
two supported queries both need an index.

Revision ID: 71486b5b74f3
Revises: 0003_expert_user_unique
Create Date: 2026-09-27 15:32:12.365709
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0004_login_attempt_identifier'
down_revision: str | None = '0003_expert_user_unique'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_attempts', sa.Column('identifier_used', sa.String(length=320), nullable=True))
    op.create_index(op.f('ix_login_attempts_identifier_used'), 'login_attempts', ['identifier_used'], unique=False)
    op.create_index('ix_login_attempts_ip_time', 'login_attempts', ['ip_address', 'attempted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_login_attempts_ip_time', table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_identifier_used'), table_name='login_attempts')
    op.drop_column('login_attempts', 'identifier_used')
    # ### end Alembic commands ###
