import '../models/condition_models.dart';

class ConditionContent {
  ConditionContent._();

  static const List<ConditionReference> references = [
    ConditionReference(
      id: 'penn-state-diagnosis',
      publisher: 'Penn State Extension',
      title: 'Diagnosing a Plant Problem 101',
      url: 'https://extension.psu.edu/diagnosing-a-plant-problem-101',
    ),
    ConditionReference(
      id: 'uc-powdery-mildew',
      publisher: 'UC IPM',
      title: 'Powdery Mildew',
      url: 'https://ipm.ucanr.edu/home-and-landscape/powdery-mildew/',
    ),
    ConditionReference(
      id: 'uc-downy-mildew',
      publisher: 'UC IPM',
      title: 'Downy Mildew',
      url: 'https://ipm.ucanr.edu/home-and-landscape/downy-mildew/',
    ),
    ConditionReference(
      id: 'umn-rust',
      publisher: 'UMN Extension',
      title: 'Rust in the Flower Garden',
      url: 'https://extension.umn.edu/plant-diseases/rust-flower-garden',
    ),
    ConditionReference(
      id: 'umn-anthracnose',
      publisher: 'UMN Extension',
      title: 'Anthracnose of Shade Trees',
      url: 'http://extension.umn.edu/node/12806',
    ),
    ConditionReference(
      id: 'umn-gray-mold',
      publisher: 'UMN Extension',
      title: 'Gray Mold in the Flower Garden',
      url: 'http://extension.umn.edu/node/11141',
    ),
    ConditionReference(
      id: 'umn-damping-off',
      publisher: 'UMN Extension',
      title: 'How to Prevent Seedling Damping-Off',
      url: 'https://extension.umn.edu/garden-and-home/yard-and-garden/gardening-in-minnesota/yard-and-garden-problems/how-to-prevent-seedling-damping-off',
    ),
    ConditionReference(
      id: 'umn-watering-houseplants',
      publisher: 'UMN Extension',
      title: 'Watering Houseplants',
      url:
          'https://extension.umn.edu/yard-and-garden-news/watering-houseplants',
    ),
    ConditionReference(
      id: 'umn-bacterial-spot',
      publisher: 'UMN Extension',
      title: 'Bacterial Spot of Tomato and Pepper',
      url: 'https://extension.umn.edu/disease-management/bacterial-spot-tomato-and-pepper',
    ),
    ConditionReference(
      id: 'umn-fire-blight',
      publisher: 'UMN Extension',
      title: 'Fire Blight',
      url: 'https://extension.umn.edu/garden-and-home/yard-and-garden/gardening-in-minnesota/yard-and-garden-problems/fire-blight',
    ),
    ConditionReference(
      id: 'umn-crown-gall',
      publisher: 'UMN Extension',
      title: 'Crown Gall',
      url: 'https://extension.umn.edu/garden-and-home/yard-and-garden/gardening-in-minnesota/yard-and-garden-problems/crown-gall',
    ),
    ConditionReference(
      id: 'umn-tomato-viruses',
      publisher: 'UMN Extension',
      title: 'Tomato Viruses',
      url: 'https://extension.umn.edu/agriculture/specialty-crops/vegetable-farming/disease-management/tomato-viruses',
    ),
    ConditionReference(
      id: 'uc-spider-mites',
      publisher: 'UC IPM',
      title: 'Spider Mites',
      url: 'https://ipm.ucanr.edu/home-and-landscape/spider-mites/',
    ),
    ConditionReference(
      id: 'uc-aphids',
      publisher: 'UC IPM',
      title: 'Aphids',
      url: 'https://ipm.ucanr.edu/home-and-landscape/aphids/',
    ),
    ConditionReference(
      id: 'uc-thrips',
      publisher: 'UC IPM',
      title: 'Thrips',
      url: 'https://ipm.ucanr.edu/home-and-landscape/thrips/',
    ),
    ConditionReference(
      id: 'uc-whiteflies',
      publisher: 'UC IPM',
      title: 'Whiteflies',
      url: 'https://ipm.ucanr.edu/home-and-landscape/whiteflies/',
    ),
    ConditionReference(
      id: 'umn-indoor-insects',
      publisher: 'UMN Extension',
      title: 'Managing Insects on Indoor Plants',
      url: 'https://extension.umn.edu/garden-and-home/yard-and-garden/yard-and-garden-insects/insects-on-indoor-plants',
    ),
    ConditionReference(
      id: 'csu-iron-chlorosis',
      publisher: 'Colorado State University Extension',
      title: 'Iron Chlorosis of Woody Plants',
      url: 'https://extension.colostate.edu/resource/iron-chlorosis-of-woody-plants/',
    ),
    ConditionReference(
      id: 'umn-seedlings',
      publisher: 'UMN Extension',
      title: 'The Case of the Curious Leggy, Yellow Seedlings',
      url: 'https://extension.umn.edu/news/case-curious-leggy-yellow-seedlings',
    ),
    ConditionReference(
      id: 'umn-tomato-disorders',
      publisher: 'UMN Extension',
      title: 'Tomato Disorders',
      url: 'https://extension.umn.edu/garden-problems/tomato-disorders',
    ),
    ConditionReference(
      id: 'umn-diagnostic-leaves',
      publisher: 'UMN Extension',
      title: 'Plant Diagnostic: Leaf Discoloration and Spots',
      url: 'https://apps.extension.umn.edu/garden/diagnose/plant/annualperennial/impatiens/leavesdiscolored.html',
    ),
    ConditionReference(
      id: 'umn-watering-vegetable',
      publisher: 'UMN Extension',
      title: 'Watering the Vegetable Garden',
      url: 'https://extension.umn.edu/gardening-minnesota/watering-vegetable-garden',
    ),
    ConditionReference(
      id: 'umn-cold-injury',
      publisher: 'UMN Extension',
      title: 'Plant Diagnostic: Cold Injury and Leaf Discoloration',
      url: 'https://apps.extension.umn.edu/garden/diagnose/plant/vegetable/tomato/leavesdiscolored.html',
    ),
    ConditionReference(
      id: 'osu-pesticide-label',
      publisher: 'Oregon State University Extension',
      title: 'How to Read a Pesticide Label',
      url: 'https://extension.oregonstate.edu/catalog/em-9410-how-read-pesticide-label-guide-small-beginning-farmers',
    ),
    ConditionReference(
      id: 'umn-managing-diseases',
      publisher: 'UMN Extension',
      title: 'Managing Plant Diseases in the Home Garden',
      url: 'https://extension.umn.edu/garden-and-home/yard-and-garden/gardening-in-minnesota/yard-and-garden-problems/managing-plant-diseases-in-the-home-garden',
    ),
  ];

  static const List<String> categories = [
    'Fungal',
    'Oomycete',
    'Bacterial',
    'Viral',
    'Pest',
    'Physiological',
    'Abiotic',
    'Nutrient',
  ];

  static const List<PlantCondition> conditions = [
    PlantCondition(
      id: 'powdery-mildew',
      commonName: 'Powdery mildew',
      scientificName: 'Powdery mildew fungi (Erysiphe spp. and relatives)',
      category: 'Fungal',
      symptoms: 'White or gray powder on either leaf surface, petioles, shoots, or buds; yellowing, distortion, and premature drop can follow.',
      likelyCauses: 'Obligate fungal growth is favored by moderate temperatures, shade, dense growth, poor airflow, and sometimes excess nitrogen.',
      lookAlikes: 'Downy mildew, edema or dried spray residue, natural variegation, and ordinary dust.',
      prevention: 'Use resistant varieties where available, provide light and spacing, water soil rather than repeatedly wetting leaves, and avoid unnecessary nitrogen.',
      culturalTreatment: 'Improve airflow and remove limited infections when practical. Do not remove more than about one-third of a plant’s foliage at once, and clean tools between plants.',
      treatmentTags: ['C', 'M', 'P'],
      escalation: 'Ask for local extension or diagnostic help when infection is recurring or severe, affects a high-value plant, or causes substantial crop loss.',
      urgentWarning: 'Sudden wilt or whole-plant collapse is not typical of powdery mildew and should prompt investigation of another cause.',
      referenceIds: ['penn-state-diagnosis', 'uc-powdery-mildew'],
    ),
    PlantCondition(
      id: 'downy-mildew',
      commonName: 'Downy mildew',
      scientificName:
          'Downy mildew oomycetes (Peronospora, Bremia, and Plasmopara spp.)',
      category: 'Oomycete',
      symptoms: 'Angular yellow lesions often bounded by veins, with gray, purple, or white sporulation mainly on leaf undersides; leaves can collapse and drop.',
      likelyCauses: 'These water-loving oomycetes spread through infected material, splashing water, and airflow, and are favored by cool, wet, humid conditions.',
      lookAlikes: 'Powdery mildew, bacterial leaf spot, nutrient deficiency, and chemical injury.',
      prevention: 'Choose resistant varieties, improve air circulation, reduce humidity, and use drip or soil-level watering instead of frequent overhead irrigation.',
      culturalTreatment: 'Remove infected plants or tissue promptly and dispose of it according to local waste guidance. Keep remaining plants dry and monitor new growth closely.',
      treatmentTags: ['C', 'M', 'P'],
      escalation: 'Escalate when spread is rapid, a susceptible crop is heavily affected, or plants begin to collapse; seek confirmation before using a product.',
      urgentWarning: 'Rapid canopy loss or widespread collapse requires prompt isolation and local diagnostic advice.',
      referenceIds: ['penn-state-diagnosis', 'uc-downy-mildew'],
    ),
    PlantCondition(
      id: 'rust',
      commonName: 'Rust',
      scientificName: 'Rust fungi (order Pucciniales)',
      category: 'Fungal',
      symptoms: 'Yellow, orange, red, or brown spots with raised powdery pustules, usually on leaf undersides; severe infection can cause yellowing and early leaf drop.',
      likelyCauses: 'Rust spores arrive on wind or infected plant material, while leaf wetness and humid weather favor germination and infection.',
      lookAlikes: 'Spider-mite stippling, thrips injury, bacterial or fungal leaf spots, and normal autumn color change.',
      prevention: 'Inspect plants before purchase, choose resistant varieties when possible, water at the base, improve spacing and airflow, and remove infected debris.',
      culturalTreatment: 'Remove infected leaves without stripping the plant and clear fallen material. Keep foliage dry when working in the garden and record whether the problem returns each season.',
      treatmentTags: ['C', 'M', 'P'],
      escalation: 'Escalate for extensive or recurring infection, fruit-crop loss, or high-value ornamentals so local timing and product options can be reviewed.',
      urgentWarning: 'Mild spotting is usually not an emergency; rapid defoliation, stem lesions, or crop-threatening spread needs prompt advice.',
      referenceIds: ['penn-state-diagnosis', 'umn-rust'],
    ),
    PlantCondition(
      id: 'anthracnose',
      commonName: 'Anthracnose',
      scientificName: 'Host-specific fungi, including Colletotrichum spp.',
      category: 'Fungal',
      symptoms: 'Irregular tan-to-brown leaf spots, cupping or distortion, twig lesions, and premature defoliation; some hosts develop dark cankers.',
      likelyCauses: 'Many anthracnose fungi overwinter in fallen leaves or twigs, with cool, wet weather and splash-dispersed spores increasing infection.',
      lookAlikes: 'Frost injury, bacterial leaf spot, other fungal leaf spots, and physical damage.',
      prevention: 'Remove fallen leaves, reduce leaf wetness, water at the base, increase canopy airflow, and avoid working among plants while foliage is wet.',
      culturalTreatment: 'Prune clearly dead or infected twigs during suitable dry weather, disinfect tools between cuts, and avoid fertilizing unless a soil test shows a need.',
      treatmentTags: ['C', 'M', 'P'],
      escalation: 'Escalate for repeated severe defoliation, dogwood or other susceptible stem cankers, girdling branches, or trunk involvement.',
      urgentWarning: 'A canker that is girdling a main branch or trunk is a structural threat and warrants a qualified arborist or extension service.',
      referenceIds: ['penn-state-diagnosis', 'umn-anthracnose'],
    ),
    PlantCondition(
      id: 'gray-mold',
      commonName: 'Gray mold',
      scientificName: 'Botrytis cinerea',
      category: 'Fungal',
      symptoms: 'Brown or black lesions on flowers, leaves, and stems, often with gray fuzzy sporulation in humid weather; old, wounded, or fallen tissue is commonly affected.',
      likelyCauses: 'Botrytis grows on damaged or dying tissue and produces abundant spores in cool, humid, poorly ventilated conditions.',
      lookAlikes: 'Other fungal blights, fruit rots, frost injury, and physical tissue damage.',
      prevention: 'Space and thin plants, water early at the soil, avoid overhead irrigation, remove dead flowers and leaves, and handle plants gently to limit wounds.',
      culturalTreatment: 'Remove infected material, improve ventilation, and prune when foliage is dry. Dispose of heavily infected tissue rather than leaving it in a cool compost pile.',
      treatmentTags: ['C', 'M'],
      escalation: 'Escalate if stems are girdled, plants collapse, or a food crop is heavily affected; repeated flower and fruit losses need local diagnosis.',
      urgentWarning: 'Rapid stem or crown spread with whole-plant collapse is the urgent warning pattern.',
      referenceIds: ['penn-state-diagnosis', 'umn-gray-mold'],
    ),
    PlantCondition(
      id: 'damping-off',
      commonName: 'Damping-off',
      scientificName: 'Pythium, Rhizoctonia, and Fusarium spp.',
      category: 'Fungal',
      symptoms: 'Seedlings may fail to emerge, collapse at the soil line, or develop water-soaked, thin, translucent stems and gray-brown roots.',
      likelyCauses: 'Several pathogens thrive in cool, wet, poorly drained media; excess fertilizer, low light, overcrowding, and reused contaminated soil increase risk.',
      lookAlikes: 'Cutworm damage, transplant shock, stem compression, mechanical injury, and salt damage.',
      prevention: 'Use clean containers and fresh, well-drained media, provide appropriate light, avoid saturated soil and overfertilization, and sanitize reusable trays.',
      culturalTreatment: 'Discard affected seedlings and contaminated media rather than composting them. Improve drainage, airflow, and seed-starting conditions before replanting.',
      treatmentTags: ['C', 'M'],
      escalation: 'Escalate when much of a tray or stand collapses or losses recur in a new batch; recurring losses may need laboratory or extension testing.',
      urgentWarning: 'Most collapsed seedlings cannot be rescued; protect the remaining plants and stop reusing the affected medium.',
      referenceIds: ['penn-state-diagnosis', 'umn-damping-off'],
    ),
    PlantCondition(
      id: 'root-rot',
      commonName: 'Root rot',
      scientificName:
          'Waterlogging and oxygen loss with host-specific root pathogens',
      category: 'Fungal',
      symptoms: 'Wilting despite moist soil, yellowing, weak growth, brown or mushy roots, poor drainage, and plants that lift or collapse easily.',
      likelyCauses: 'Saturated soil reduces oxygen around roots; pathogens such as Pythium, Phytophthora, Fusarium, or Rhizoctonia may contribute when conditions favor them.',
      lookAlikes: 'Drought stress, nutrient or salt injury, vascular wilt, stem damage, and normal wilting during heat.',
      prevention: 'Use containers with drainage holes, choose appropriate soil, never leave standing water in a saucer, and schedule watering for the plant and season.',
      culturalTreatment: 'Correct drainage, move the plant out of standing water, and repot into fresh appropriate media when roots or drainage are compromised. Remove decayed roots with clean tools.',
      treatmentTags: ['C', 'M', 'D'],
      escalation: 'Escalate for rapid decline, widespread wilt in wet soil, root odor or decay, or loss of a young or high-value plant.',
      urgentWarning: 'A collapsing plant with mushy roots needs prompt isolation; do not keep adding water to an already saturated root zone.',
      referenceIds: ['penn-state-diagnosis', 'umn-watering-houseplants'],
    ),
    PlantCondition(
      id: 'bacterial-leaf-spot',
      commonName: 'Bacterial leaf spot',
      scientificName: 'Xanthomonas and related bacteria',
      category: 'Bacterial',
      symptoms: 'Small brown or black circular spots, often with yellow halos; centers may fall out, and fruit can develop raised scabby lesions.',
      likelyCauses: 'Bacteria spread through infected seed or transplants, rain splash, tools, and handling wet plants; warm, humid conditions favor disease.',
      lookAlikes: 'Early blight, Septoria leaf spot, bacterial speck, mite or thrips injury, and chemical spots.',
      prevention: 'Start with reputable clean seed or transplants, rotate susceptible crops, keep foliage dry, use drip or base watering, space plants, and avoid handling wet plants.',
      culturalTreatment: 'Remove symptomatic leaves and crop debris, sanitize tools, and avoid saving seed from affected fruit. Do not compost infected material unless local guidance says the pile reaches pathogen-killing temperatures.',
      treatmentTags: ['C', 'M', 'P', 'D'],
      escalation: 'Escalate for rapid spread, fruit lesions, or an edible-crop decision. UMN advises not eating fruit affected by bacterial spot.',
      urgentWarning: 'A rapidly spreading disease in a food crop should be isolated and reported to local extension or a plant diagnostic service.',
      referenceIds: ['penn-state-diagnosis', 'umn-bacterial-spot'],
    ),
    PlantCondition(
      id: 'fire-blight',
      commonName: 'Fire blight',
      scientificName: 'Erwinia amylovora',
      category: 'Bacterial',
      symptoms: 'Blackened blossoms, wilted gray-green shoots bending into a shepherd’s crook, dead leaves, dark cankers, and honey-colored ooze in wet weather.',
      likelyCauses: 'The bacterium infects susceptible Rosaceae hosts during bloom, warm wet weather, or through wounds; nearby hosts and regional conditions matter.',
      lookAlikes: 'Frost or cold injury, herbicide injury, other shoot blights, sunscald, and mechanical damage.',
      prevention: 'Choose less-susceptible cultivars, avoid excessive nitrogen and heavy pruning, and remove infected material during the appropriate local growing-season window.',
      culturalTreatment: 'Remove infected shoots well below visible symptoms and into healthy wood. Larger branch infections may need professional pruning; disinfect tools between cuts.',
      treatmentTags: ['C', 'M', 'P', 'D'],
      escalation: 'Urgent if infection reaches the main trunk, spreads rapidly, or affects a young or high-value tree; contact a local arborist or extension service.',
      urgentWarning: 'A main-trunk canker or rapidly advancing infection can threaten the entire tree and should not be managed as a routine leaf spot.',
      referenceIds: ['penn-state-diagnosis', 'umn-fire-blight'],
    ),
    PlantCondition(
      id: 'crown-gall',
      commonName: 'Crown gall',
      scientificName: 'Agrobacterium tumefaciens complex and related species',
      category: 'Bacterial',
      symptoms: 'Rough, woody, tumor-like galls on roots, the crown, trunk, or branches, sometimes followed by stunting, wilt, drought sensitivity, or decline.',
      likelyCauses: 'Soilborne bacteria enter through wounds, especially during planting; contaminated soil, tools, and plant material can spread them.',
      lookAlikes: 'Insect galls, burlaps, callus tissue, root or stem wounds, and some viral or fungal growths.',
      prevention: 'Inspect roots and crowns before planting, reject galled plants, minimize root wounds, and avoid planting highly susceptible species in infested sites.',
      culturalTreatment: 'Monitor established plants, maintain good drainage and care, and remove a young severely affected plant when local guidance recommends removal.',
      treatmentTags: ['C', 'M', 'B', 'D'],
      escalation: 'Escalate for young plants, galls encircling the main stem, or decline after planting; mature trees may tolerate limited galls.',
      urgentWarning: 'A girdling gall or rapid decline threatens the plant’s transport system and needs professional assessment.',
      referenceIds: ['penn-state-diagnosis', 'umn-crown-gall'],
    ),
    PlantCondition(
      id: 'mosaic-virus',
      commonName: 'Mosaic and related viruses',
      scientificName: 'Plant viruses, including ToMV, TMV, CMV, ZYMV, and SqMV',
      category: 'Viral',
      symptoms: 'Mottled light and dark or yellow and green leaves, distortion, stunting, uneven fruit ripening, rings, discoloration, or internal browning.',
      likelyCauses: 'Viruses spread differently by host and virus, including infected seed, contact, tools, weeds, and insect vectors; not every mottling pattern is viral.',
      lookAlikes: 'Herbicide injury, aphid or thrips feeding, mite damage, nutrient imbalance, and natural leaf patterns.',
      prevention: 'Use certified plants and resistant varieties where available, remove weeds that may harbor viruses, clean hands and tools, and manage vectors carefully.',
      culturalTreatment: 'Isolate suspected plants, remove them when local guidance recommends removal, and avoid propagating from symptomatic material. No pesticide cures an infected plant.',
      treatmentTags: ['C', 'M', 'D'],
      escalation: 'Any suspected virus should be isolated and sent for laboratory confirmation; escalate rapidly for a high-value or widespread crop.',
      urgentWarning: 'Widespread mottling, distortion, or fruit symptoms in a crop is a containment concern, not a sign to apply a broad pesticide.',
      referenceIds: [
        'penn-state-diagnosis',
        'umn-tomato-viruses',
        'umn-managing-diseases',
      ],
    ),
    PlantCondition(
      id: 'spider-mites',
      commonName: 'Spider mites',
      scientificName: 'Tetranychus and related mites',
      category: 'Pest',
      symptoms: 'Fine stippling, bronzing, bleaching, yellowing, leaf drop, fine webbing, and tiny moving mites or eggs on leaf undersides.',
      likelyCauses: 'Mites thrive in hot, dry, dusty conditions and are favored by stressed plants and the absence of natural enemies.',
      lookAlikes: 'Thrips, leafhoppers, nutrient stress, sunscald, and ordinary fine speckling from mineral residue.',
      prevention: 'Inspect leaf undersides with magnification, reduce dust, maintain even watering, and avoid broad-spectrum insecticides that can trigger mite outbreaks.',
      culturalTreatment: 'Rinse undersides with a gentle stream of water, remove badly infested foliage, and conserve lady beetles and other predators. Confirm mites before choosing a product.',
      treatmentTags: ['C', 'M', 'B', 'P'],
      escalation: 'Escalate when webbing, stippling, or defoliation is widespread, or when natural enemies have been disrupted by pesticide use.',
      urgentWarning: 'Rapid bronzing and webbing across a plant can cause substantial leaf loss quickly; isolate and inspect neighboring plants.',
      referenceIds: ['uc-spider-mites', 'umn-indoor-insects'],
    ),
    PlantCondition(
      id: 'aphids',
      commonName: 'Aphids',
      scientificName: 'Aphis, Myzus, and related aphid species',
      category: 'Pest',
      symptoms: 'Clusters of soft, pear-shaped insects on new growth, with leaf curling, distortion, yellowing, stunting, honeydew, and black sooty mold.',
      likelyCauses: 'Aphids feed on plant sap and reproduce rapidly in warm conditions; they may arrive on new plants and can transmit some viruses.',
      lookAlikes: 'Psyllids, whitefly nymphs, mites, virus symptoms, and herbicide injury.',
      prevention: 'Inspect new growth regularly, remove weeds that provide shelter, avoid excess nitrogen, and conserve predators such as lady beetles, lacewings, and parasitoids.',
      culturalTreatment: 'Dislodge aphids with water, prune heavily infested tips, and remove honeydew-producing colonies when practical. Avoid spraying flowering plants or broad-spectrum products unnecessarily.',
      treatmentTags: ['C', 'M', 'B', 'P'],
      escalation: 'Escalate for large colonies, honeydew and sooty mold, virus-like symptoms, or crop injury; monitor natural enemies before treating.',
      urgentWarning: 'Rapidly expanding colonies on new growth or a virus-susceptible crop warrant prompt containment and confirmation.',
      referenceIds: ['penn-state-diagnosis', 'uc-aphids', 'umn-indoor-insects'],
    ),
    PlantCondition(
      id: 'thrips',
      commonName: 'Thrips',
      scientificName: 'Frankliniella, Thrips, and related species',
      category: 'Pest',
      symptoms: 'Silvery streaks or scars, black fecal specks, distorted flowers, fruit scarring, and reduced growth; insects hide in buds and protected tissue.',
      likelyCauses: 'Thrips feed by rasping tissue and can move between flowers and plants; warm conditions and some virus associations increase concern.',
      lookAlikes: 'Spider mites, abrasive wind or chemical injury, virus symptoms, and mite damage.',
      prevention: 'Inspect flowers and leaf undersides, use yellow or blue sticky cards for monitoring, exclude adults with properly installed mesh or row cover, and remove heavily infested material.',
      culturalTreatment: 'Remove affected flowers or tissue, use clean plant material, and conserve predators. Avoid broad-spectrum products that also kill beneficial insects.',
      treatmentTags: ['C', 'M', 'B', 'P'],
      escalation: 'Escalate during flowering or fruit development, when virus transmission is a concern, or when damage recurs despite monitoring.',
      urgentWarning: 'Developing fruit or flowers with repeated distortion and silvery scars need prompt identification because treatment windows may be short.',
      referenceIds: ['uc-thrips', 'umn-indoor-insects'],
    ),
    PlantCondition(
      id: 'whiteflies',
      commonName: 'Whiteflies',
      scientificName: 'Bemisia, Trialeurodes, and related species',
      category: 'Pest',
      symptoms: 'Clouds of tiny white adults when disturbed, underside nymphs, sticky honeydew, sooty mold, yellowing, silvering, or drying leaves.',
      likelyCauses: 'Whiteflies feed on plant sap, especially on the underside of leaves, and can persist through warm conditions and nearby host plants.',
      lookAlikes: 'Aphids, psyllids, spider mites, edema, and ordinary dust or residue.',
      prevention: 'Inspect incoming plants, isolate them, reduce dust, manage ants, and use yellow sticky cards to monitor rather than relying on them as a control.',
      culturalTreatment: 'Remove heavily infested leaves or plants after harvest where appropriate, wash foliage when practical, and conserve natural enemies. Avoid broad-spectrum sprays.',
      treatmentTags: ['C', 'M', 'B', 'P'],
      escalation: 'Escalate for heavy nymph populations, virus symptoms, or repeated crop losses; remove and isolate the source plants.',
      urgentWarning: 'A cloud of adults with extensive underside nymphs and honeydew is a fast-moving infestation that needs containment.',
      referenceIds: ['uc-whiteflies', 'umn-indoor-insects'],
    ),
    PlantCondition(
      id: 'scale-mealybugs',
      commonName: 'Scale and mealybugs',
      scientificName:
          'Scale insects (Coccoidea) and mealybugs (Pseudococcidae)',
      category: 'Pest',
      symptoms: 'Immobile brown, gray, or white bumps; cottony white filaments; honeydew, yellowing, stunting, wilt, and sooty mold.',
      likelyCauses: 'Sap-sucking insects settle on stems, leaf veins, and nodes; ants may protect them from natural enemies, while warm conditions favor some species.',
      lookAlikes: 'Edema, fungal spots, benign plant glands, aphid wax, and small attached debris.',
      prevention: 'Isolate new plants, inspect stems and leaf undersides, avoid excess nitrogen, and conserve predatory insects and parasitoids.',
      culturalTreatment: 'Wipe or wash foliage, physically remove scale or mealybugs, prune localized infestations, and repot when soil pests are present. Use a product only after confirmation and label review.',
      treatmentTags: ['C', 'M', 'B', 'P'],
      escalation: 'Escalate when new growth is heavily infested, honeydew is widespread, or natural enemies are absent; inspect neighboring plants.',
      urgentWarning: 'Rapid spread across multiple plants or a severe infestation of a high-value plant needs prompt identification and containment.',
      referenceIds: ['penn-state-diagnosis', 'umn-indoor-insects'],
    ),
    PlantCondition(
      id: 'fungus-gnats',
      commonName: 'Fungus gnats',
      scientificName: 'Fungus-fly species such as Bradysia spp.',
      category: 'Pest',
      symptoms: 'Small dark flies around damp soil and translucent legless larvae with dark heads; adults are usually a nuisance and larvae may feed on fungi or decaying roots.',
      likelyCauses: 'Moist organic media, decaying material, and overwatering support fungus and fungus-fly life cycles; root rot can coexist.',
      lookAlikes: 'Fruit flies, springtails, drainage flies, and other small soil-surface insects.',
      prevention: 'Let the surface dry appropriately between waterings, improve drainage, remove decaying material, and use yellow sticky cards for monitoring.',
      culturalTreatment: 'Correct drainage, repot into clean media when needed, and remove standing water. A labeled Bacillus thuringiensis subspecies israelensis product targets larvae, not flying adults.',
      treatmentTags: ['C', 'M', 'B', 'P'],
      escalation: 'Escalate when larvae occur with wilt, root loss, or unexplained decline; test drainage and roots rather than assuming gnats are the primary cause.',
      urgentWarning: 'A collapsing plant with wet soil and damaged roots may have root rot, not just fungus gnats; isolate it and inspect the root zone.',
      referenceIds: ['umn-indoor-insects'],
    ),
    PlantCondition(
      id: 'edema',
      commonName: 'Edema',
      scientificName: 'Intumescence caused by excess water uptake under cool, humid conditions',
      category: 'Physiological',
      symptoms: 'Pale-green or white blisters on leaf undersides that later become brown, corny, or crusty; older leaves are often affected first.',
      likelyCauses: 'Roots take up water faster than leaves can transpire it, especially when soil stays wet and air movement is limited.',
      lookAlikes: 'Mites, scale, fungal or bacterial spots, spray injury, and some natural leaf structures.',
      prevention: 'Avoid overwatering, ensure drainage, improve air movement, manage indoor humidity, and avoid excess fertilizer, especially nitrogen.',
      culturalTreatment: 'Reduce excess watering, let the root zone drain appropriately, increase airflow, and remove severely damaged tissue only when needed. No pesticide treats edema.',
      treatmentTags: ['C', 'M'],
      escalation: 'Escalate if blistering continues after watering and drainage are corrected, or if severe cracking and plant decline occur.',
      urgentWarning: 'Widespread blistering with declining vigor needs correction of water, roots, humidity, or possible salt injury rather than a pesticide.',
      referenceIds: ['penn-state-diagnosis', 'umn-diagnostic-leaves'],
    ),
    PlantCondition(
      id: 'sunscald',
      commonName: 'Sunscald',
      scientificName: 'Heat and intense-light injury',
      category: 'Abiotic',
      symptoms: 'Bleached yellow-to-white or tan patches only on exposed leaves, fruit, or stems; tissue may become dry, brittle, or secondarily infected.',
      likelyCauses: 'Sudden exposure to intense light or heat, especially on recently moved plants, young fruit, and parts touching a hot window or wall.',
      lookAlikes: 'Cold injury, edema, chemical burn, and fungal sunscald-like lesions.',
      prevention: 'Acclimate plants gradually, use temporary shade or physical protection during extreme heat, and maintain consistent root-zone moisture.',
      culturalTreatment: 'Protect exposed tissue during the next heat event, preserve healthy foliage, and remove damaged fruit only when it is no longer useful.',
      treatmentTags: ['C', 'M'],
      escalation: 'Escalate when fruit is affected, tissue is collapsing, or repeated exposure threatens a young transplant or high-value plant.',
      urgentWarning: 'Exposed tissue that rapidly turns soft or black may have secondary infection; separate it from healthy plant material.',
      referenceIds: [
        'penn-state-diagnosis',
        'umn-diagnostic-leaves',
        'umn-cold-injury',
      ],
    ),
    PlantCondition(
      id: 'water-stress',
      commonName: 'Water stress',
      scientificName: 'Root-zone moisture deficit or waterlogging mismatch',
      category: 'Abiotic',
      symptoms: 'Wilting, drooping, curling, crisp margins, flower or fruit drop, and slow growth; soil may be dry or excessively wet if roots are damaged.',
      likelyCauses: 'Under-watering, over-watering that suffocates roots, heat and wind, container size, and poor drainage can produce similar visible symptoms.',
      lookAlikes: 'Root rot, heat stress, virus, vascular wilt, salt injury, and normal temporary wilting.',
      prevention: 'Check soil moisture rather than following a fixed calendar, use mulch, and choose containers and soil with drainage appropriate to the plant.',
      culturalTreatment: 'Water thoroughly to the root zone when dry, correct standing water or root damage, and prioritize young, flowering, and fruiting plants during heat.',
      treatmentTags: ['C', 'D'],
      escalation: 'Urgent when plants cannot recover, wilt is accompanied by collapse, or irrigation does not restore function; inspect roots and drainage.',
      urgentWarning: 'Do not keep adding water to a wilted plant until soil and roots are checked; both dry and saturated roots can produce wilt.',
      referenceIds: [
        'penn-state-diagnosis',
        'umn-watering-houseplants',
        'umn-watering-vegetable',
      ],
    ),
    PlantCondition(
      id: 'cold-injury',
      commonName: 'Cold and frost injury',
      scientificName: 'Freeze or chilling injury',
      category: 'Abiotic',
      symptoms: 'Water-soaked or blackened leaves, collapsed stems, soft or rotted fruit, and damage that may appear days after the cold event.',
      likelyCauses: 'Temperature below a plant’s tolerance, cold wind, wet tissue during freezing, and sudden changes between warm and cold conditions.',
      lookAlikes: 'Fire blight, sunscald, bacterial soft rot, insect damage, and chemical injury.',
      prevention: 'Use local frost dates, protect young plants and containers, and avoid leaving tender plants exposed when a freeze is forecast.',
      culturalTreatment: 'Wait until the dead and healthy boundary is clear, then remove dead tissue with clean tools. Protect surviving plants during the next cold event.',
      treatmentTags: ['C', 'M', 'D'],
      escalation: 'Escalate after widespread frost, tree damage, or fruit loss; get arborist or extension input for woody plants with structural injury.',
      urgentWarning: 'Blackened tissue, collapsed stems, or soft fruit should be isolated from healthy plants because secondary rot can follow.',
      referenceIds: ['penn-state-diagnosis', 'umn-cold-injury'],
    ),
    PlantCondition(
      id: 'iron-chlorosis',
      commonName: 'Iron chlorosis',
      scientificName: 'Usually reduced iron availability in high-pH, wet, or compacted soil',
      category: 'Nutrient',
      symptoms: 'Interveinal yellowing with green veins, usually first on new growth; leaves may become pale, small, scorched, or stunted.',
      likelyCauses: 'High soil pH, excess lime, poor drainage, compaction, root damage, or overwatering can make iron unavailable even when it is present.',
      lookAlikes: 'Nitrogen deficiency, manganese or zinc deficiency, herbicide injury, root damage, and natural variegation.',
      prevention: 'Test soil pH and lime content, correct drainage and compaction, select tolerant plants, and keep roots healthy.',
      culturalTreatment: 'Use a soil-test-based approach and choose an iron amendment appropriate to the plant and pH. Avoid repeated blanket fertilizer applications that can worsen nutrient imbalance.',
      treatmentTags: ['C', 'P', 'D'],
      escalation: 'Escalate for one-sided canopy decline, branch dieback, or severe and repeated annual symptoms; obtain a soil test and arborist or extension input.',
      urgentWarning: 'Progressive dieback on a branch or trunk is not solved by a fertilizer treatment alone and needs professional assessment.',
      referenceIds: ['csu-iron-chlorosis', 'penn-state-diagnosis'],
    ),
    PlantCondition(
      id: 'nitrogen-deficiency',
      commonName: 'Nitrogen deficiency',
      scientificName: 'Insufficient plant-available nitrogen',
      category: 'Nutrient',
      symptoms: 'Uniform pale-to-yellow older leaves, thin stems, and slow growth; younger leaves may remain greener than older ones.',
      likelyCauses: 'Low available nitrogen, exhausted potting mix, leaching, cold or damaged roots, and high demand during active growth.',
      lookAlikes: 'Water stress, salinity, root damage, iron deficiency, and normal lower-leaf senescence.',
      prevention: 'Use a soil or potting-mix test, refresh depleted mix, maintain drainage, and fertilize only during active growth at the label rate.',
      culturalTreatment: 'Correct root and watering problems first. If a test supports it, use an appropriate fertilizer at its labeled rate and avoid repeated unnecessary applications.',
      treatmentTags: ['C', 'P', 'D'],
      escalation: 'Escalate when symptoms persist after irrigation correction, growth remains weak, or salt injury or root damage is suspected.',
      urgentWarning: 'Rapid collapse with yellow leaves is not typical of simple nitrogen deficiency; check water, roots, and disease instead.',
      referenceIds: ['umn-seedlings', 'penn-state-diagnosis'],
    ),
    PlantCondition(
      id: 'blossom-end-rot',
      commonName: 'Blossom-end rot',
      scientificName: 'Calcium-transport disorder, often triggered by moisture or root stress',
      category: 'Physiological',
      symptoms: 'Tan-to-black, sunken or leathery lesions at the fruit’s blossom end, often followed by secondary decay.',
      likelyCauses: 'Uneven soil moisture, heat, root injury, poor pollination, excess nitrogen, and rapid fruit growth can disrupt calcium movement; soil calcium need not be low.',
      lookAlikes: 'Sunscald, fruit rot, cold injury, insect damage, and other physical fruit injuries.',
      prevention: 'Keep soil moisture relatively even, mulch, protect roots, avoid excessive nitrogen, and use soil-test-based fertilization.',
      culturalTreatment: 'Correct irrigation and root-zone stress, remove affected fruit, and avoid assuming that a routine calcium spray will solve the problem.',
      treatmentTags: ['C', 'M', 'D'],
      escalation: 'Escalate for repeated crop loss, rapid secondary rot, or widespread fruit symptoms; irrigation and root conditions need review.',
      urgentWarning: 'A spreading soft or collapsing fruit lesion should be removed promptly and checked for secondary rot rather than treated as a guaranteed calcium deficiency.',
      referenceIds: ['penn-state-diagnosis', 'umn-tomato-disorders'],
    ),
  ];

  static final Map<String, ConditionReference> _referencesById = {
    for (final reference in references) reference.id: reference,
  };

  static final Map<String, PlantCondition> _conditionsById = {
    for (final condition in conditions) condition.id: condition,
  };

  static PlantCondition? byId(String id) => _conditionsById[id];

  static ConditionReference? referenceById(String id) => _referencesById[id];

  static List<ConditionReference> referencesFor(PlantCondition condition) {
    return condition.referenceIds
        .map(referenceById)
        .whereType<ConditionReference>()
        .toList(growable: false);
  }

  static String categoryLabel(String category) {
    return switch (category) {
      'Fungal' => 'Fungal',
      'Oomycete' => 'Oomycete',
      'Bacterial' => 'Bacterial',
      'Viral' => 'Viral',
      'Pest' => 'Pest',
      'Physiological' => 'Physiological / nutrient movement',
      'Abiotic' => 'Abiotic / environmental',
      'Nutrient' => 'Nutrient',
      _ => category,
    };
  }
}
